export const PITCH_FREQUENCIES: Record<string, number> = {
  C4: 261.63,
  'C♯4': 277.18,
  'D♭4': 277.18,
  D4: 293.66,
  'D♯4': 311.13,
  'E♭4': 311.13,
  E4: 329.63,
  F4: 349.23,
  'F♯4': 369.99,
  'G♭4': 369.99,
  G4: 392.0,
  'G♯4': 415.30,
  'A♭4': 415.30,
  A4: 440.0,
  'A♯4': 466.16,
  'B♭4': 466.16,
  B4: 493.88
}

export const NOTE_NAME_TO_FREQ: Record<string, number> = {
  C: PITCH_FREQUENCIES.C4,
  'C♯': PITCH_FREQUENCIES['C♯4'],
  'D♭': PITCH_FREQUENCIES['D♭4'],
  D: PITCH_FREQUENCIES.D4,
  'D♯': PITCH_FREQUENCIES['D♯4'],
  'E♭': PITCH_FREQUENCIES['E♭4'],
  E: PITCH_FREQUENCIES.E4,
  F: PITCH_FREQUENCIES.F4,
  'F♯': PITCH_FREQUENCIES['F♯4'],
  'G♭': PITCH_FREQUENCIES['G♭4'],
  G: PITCH_FREQUENCIES.G4,
  'G♯': PITCH_FREQUENCIES['G♯4'],
  'A♭': PITCH_FREQUENCIES['A♭4'],
  A: PITCH_FREQUENCIES.A4,
  'A♯': PITCH_FREQUENCIES['A♯4'],
  'B♭': PITCH_FREQUENCIES['B♭4'],
  B: PITCH_FREQUENCIES.B4,
  'B♯': PITCH_FREQUENCIES.C4,
  'D𝄫': PITCH_FREQUENCIES.C4,
  'B𝄪': PITCH_FREQUENCIES['C♯4'],
  'C𝄪': PITCH_FREQUENCIES.D4,
  'E𝄫': PITCH_FREQUENCIES.D4,
  'F𝄫': PITCH_FREQUENCIES['E♭4'],
  'F♭': PITCH_FREQUENCIES.E4,
  'D𝄪': PITCH_FREQUENCIES.E4,
  'E♯': PITCH_FREQUENCIES.F4,
  'G𝄫': PITCH_FREQUENCIES.F4,
  'E𝄪': PITCH_FREQUENCIES['F♯4'],
  'F𝄪': PITCH_FREQUENCIES.G4,
  'A𝄫': PITCH_FREQUENCIES.G4,
  'G𝄪': PITCH_FREQUENCIES.A4,
  'B𝄫': PITCH_FREQUENCIES.A4,
  'C𝄫': PITCH_FREQUENCIES['B♭4'],
  'A𝄪': PITCH_FREQUENCIES.B4,
  'C♭': PITCH_FREQUENCIES.B4,
  'C#': PITCH_FREQUENCIES['C♯4'],
  Db: PITCH_FREQUENCIES['D♭4'],
  'D#': PITCH_FREQUENCIES['D♯4'],
  Eb: PITCH_FREQUENCIES['E♭4'],
  'F#': PITCH_FREQUENCIES['F♯4'],
  Gb: PITCH_FREQUENCIES['G♭4'],
  'G#': PITCH_FREQUENCIES['G♯4'],
  Ab: PITCH_FREQUENCIES['A♭4'],
  'A#': PITCH_FREQUENCIES['A♯4'],
  Bb: PITCH_FREQUENCIES['B♭4'],
  'B#': PITCH_FREQUENCIES.C4,
  'Dbb': PITCH_FREQUENCIES.C4,
  'B##': PITCH_FREQUENCIES['C♯4'],
  'C##': PITCH_FREQUENCIES.D4,
  'Ebb': PITCH_FREQUENCIES.D4,
  'Fbb': PITCH_FREQUENCIES['E♭4'],
  'Fb': PITCH_FREQUENCIES.E4,
  'D##': PITCH_FREQUENCIES.E4,
  'E#': PITCH_FREQUENCIES.F4,
  'Gbb': PITCH_FREQUENCIES.F4,
  'E##': PITCH_FREQUENCIES['F♯4'],
  'F##': PITCH_FREQUENCIES.G4,
  'Abb': PITCH_FREQUENCIES.G4,
  'G##': PITCH_FREQUENCIES.A4,
  'Bbb': PITCH_FREQUENCIES.A4,
  'Cbb': PITCH_FREQUENCIES['B♭4'],
  'A##': PITCH_FREQUENCIES.B4,
  'Cb': PITCH_FREQUENCIES.B4
}

const getNoteFrequency = (noteName: string): number =>
  NOTE_NAME_TO_FREQ[noteName] ?? PITCH_FREQUENCIES.C4

export const calculatePlaybackRate = (targetNoteName: string): number => {
  const targetFreq = getNoteFrequency(targetNoteName)
  const baseFreq = PITCH_FREQUENCIES.C4
  return targetFreq / baseFreq
}
