name: Deploy to Staging

on:
  push:
    branches-ignore:
      - main
      - staging
  pull_request:
    branches:
      - staging
  workflow_dispatch:



jobs:
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on PR
        run: |
          echo "🚀 Staging PR created! Test your changes on staging before merging to main."


